/**
 * OpenCPS is the open source Core Public Services software
 * Copyright (C) 2016-present OpenCPS community
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 */

package org.opencps.feedback.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FeedBack service. Represents a row in the &quot;opencps_feedback&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.opencps.feedback.model.impl.FeedBackModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.opencps.feedback.model.impl.FeedBackImpl}.
 * </p>
 *
 * @author khoavd
 * @see FeedBack
 * @see org.opencps.feedback.model.impl.FeedBackImpl
 * @see org.opencps.feedback.model.impl.FeedBackModelImpl
 * @generated
 */
public interface FeedBackModel extends BaseModel<FeedBack>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a feed back model instance should use the {@link FeedBack} interface instead.
	 */

	/**
	 * Returns the primary key of this feed back.
	 *
	 * @return the primary key of this feed back
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this feed back.
	 *
	 * @param primaryKey the primary key of this feed back
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the feedback ID of this feed back.
	 *
	 * @return the feedback ID of this feed back
	 */
	public long getFeedbackId();

	/**
	 * Sets the feedback ID of this feed back.
	 *
	 * @param feedbackId the feedback ID of this feed back
	 */
	public void setFeedbackId(long feedbackId);

	/**
	 * Returns the group ID of this feed back.
	 *
	 * @return the group ID of this feed back
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this feed back.
	 *
	 * @param groupId the group ID of this feed back
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this feed back.
	 *
	 * @return the company ID of this feed back
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this feed back.
	 *
	 * @param companyId the company ID of this feed back
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this feed back.
	 *
	 * @return the user ID of this feed back
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this feed back.
	 *
	 * @param userId the user ID of this feed back
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this feed back.
	 *
	 * @return the user uuid of this feed back
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this feed back.
	 *
	 * @param userUuid the user uuid of this feed back
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this feed back.
	 *
	 * @return the user name of this feed back
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this feed back.
	 *
	 * @param userName the user name of this feed back
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this feed back.
	 *
	 * @return the create date of this feed back
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this feed back.
	 *
	 * @param createDate the create date of this feed back
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this feed back.
	 *
	 * @return the modified date of this feed back
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this feed back.
	 *
	 * @param modifiedDate the modified date of this feed back
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the full name of this feed back.
	 *
	 * @return the full name of this feed back
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this feed back.
	 *
	 * @param fullName the full name of this feed back
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the email of this feed back.
	 *
	 * @return the email of this feed back
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this feed back.
	 *
	 * @param email the email of this feed back
	 */
	public void setEmail(String email);

	/**
	 * Returns the feed back of this feed back.
	 *
	 * @return the feed back of this feed back
	 */
	@AutoEscape
	public String getFeedBack();

	/**
	 * Sets the feed back of this feed back.
	 *
	 * @param feedBack the feed back of this feed back
	 */
	public void setFeedBack(String feedBack);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.opencps.feedback.model.FeedBack feedBack);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.opencps.feedback.model.FeedBack> toCacheModel();

	@Override
	public org.opencps.feedback.model.FeedBack toEscapedModel();

	@Override
	public org.opencps.feedback.model.FeedBack toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}